server: 
  tomcat: 
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9001

# DataSource
spring: 
  datasource: 
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://rm-2zeusd974246esxc95o.mysql.rds.aliyuncs.com:3306/epidemic?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8     
      #url: jdbc:mysql://localhost:3306/yianmarket?useUnicode=true&characterEncoding=utf8&useSSL=false
      #url: jdbc:mysql://rm-2ze46rh92b991z4y6wo.mysql.rds.aliyuncs.com:3306/yianmarket?useUnicode=true&characterEncoding=utf8&useSSL=false  
      #url: jdbc:mysql://124.207.242.89/epidemic?useUnicode=true&characterEncoding=utf8&useSSL=false
      url: jdbc:mysql://localhost/epidemic?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: yian@123
      #username: aeonmed
      #password: aeonmed@123
      #username: root
      #password: aeonroot
      max-idle: 10
      max-wait: 60000
      min-idle: 5
      initial-size: 5
      filters: stat,wall,log4j,config
      max-active: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  # spring boot admin
  application: 
    name: yian-admin

  boot: 
    admin: 
      client: 
         #url: "http://172.10.1.169:9001"
          url: "http://localhost:9001"
          
